# -*- coding: utf-8 -*-
"""1- Two Sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLKTdrit_naJrI5Xq69qlJ0j-9_1ormH

#**1. Two Sum**

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.


You may assume that each input would have exactly one solution, and you may not use the same element twice.


You can return the answer in any order.



Example 1:


Input: nums = [2,7,11,15], target = 9

Output: [0,1]

Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

Example 2:

Input: nums = [3,2,4], target = 6

Output: [1,2]

Example 3:

Input: nums = [3,3], target = 6

Output: [0,1]


Constraints:

2 <= nums.length <= 104

-109 <= nums[i] <= 109

-109 <= target <= 109

Only one valid answer exists.
"""

class Solution:
    def twoSum(self, nums: list[int], target: int) -> list[int]:
        m = {}

        for i,x in enumerate(nums):
            y=target-x
            if y in m:
                return[m[y], i]
            m[x] = i